### ISSUE TITLE
Missing styles

### ISSUE THREAD

**Issue by Mottie** [gregwhitworth/scrollWidthPolyfill#1]
I've been working with the component [textarea-caret-position](https://github.com/component/textarea-caret-position/blob/master/index.js) code. It has a list of numerous styles that do not appear to be included with this polyfill. Not all of the same styles listed there are needed, but a bunch might be needed... for example:
- `fontStyle`
- `fontVariant`
- `fontStretch`
- `fontSizeAdjust`
- `textTransform`
- `textIndent`
- `textDecoration`
- `letterSpacing`
- `wordSpacing`
- `tabSize` (for textarea)

**Comment by gregwhitworth** [comment]
Thanks for this, I switched to using computedStyle which will ensure that all of the styles applied to the element will get moved over if it is a textarea for measuring. Please let me know if you catch anything, I appreciate the feedback!
