### ISSUE TITLE
Feature test

### ISSUE THREAD

**Issue by LeaVerou** [gregwhitworth/scrollWidthPolyfill#3]
There’s a very simple feature test here (to see if the polyfill is needed): Just add an input with a value, set its width to zero, its paddings/borders to 0 and test if scrollWidth is > 0. I haven’t parsed all this code for your feature test, but why such a long test?

**Comment by gregwhitworth** [comment]
Not sure why I didn't see that one, that's the primary test case we've been battling with; but that's also why code reviews are so great! Thank you for the feedback, I've updated it based on your suggestion and ensured that the test continue to pass as expected in IE/Edge/Chrome/FF. Thanks!!
